// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9Ril8Yi-EpeS3Aq-t3kPXSwP_gudeg0',
    appId: '1:887109667381:web:c725a18bbf6507f3b8bf7c',
    messagingSenderId: '887109667381',
    projectId: 'chatit-1601c',
    authDomain: 'chatit-1601c.firebaseapp.com',
    storageBucket: 'chatit-1601c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR87CZ2YxgdC8gWYEkZAXEzIfdliMR_8I',
    appId: '1:887109667381:android:fdef29056f48813fb8bf7c',
    messagingSenderId: '887109667381',
    projectId: 'chatit-1601c',
    storageBucket: 'chatit-1601c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO5p9WkodXS-X_uJ8_qtWgEQW7i14yNQE',
    appId: '1:887109667381:ios:ff7511be9eb36133b8bf7c',
    messagingSenderId: '887109667381',
    projectId: 'chatit-1601c',
    storageBucket: 'chatit-1601c.appspot.com',
    iosBundleId: 'com.example.chatwm',
  );
}
